### ISSUE TITLE
Support for iOS 11

### ISSUE THREAD

**Issue by urthling** [tuarua/Swift-IOS-ANE#10]
I've been struggling with XCode 9.0/iOS 11 - and I just noticed your commit about XCode 9 not being supported, so just wanted to check with you about my experience so far and share one solution to a problem I had including iOS 11.

I ran into an issue including iOS 11 in my main project - this was solved here:
https://forums.adobe.com/thread/2382667

I was able to build the ANE and I'm targeting iOS 10 - however the error I'm seeing when including the ANE in my project is this:

ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/FreSwift.framework/FreSwift) for architecture arm64
ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/FreSwift.framework/FreSwift) for architecture armv7
Compilation failed while executing : ld64

Is this one of the reasons that XCode 9 is not supported or is this something that you might know how to resolve?

This project rocks btw, love the idea of being able to use Swift!  Thank you for sharing.

**Comment by tuarua** [comment]
Hi,
The reason why Xcode 9 is not supported is because ADT is not signing the Swift 4.0 dylibs correctly for some reason. ADT completes without error but I get invalid signature when the app runs.
The Swift 3 dylibs get signed fine.
So currently only Xcode 8.3 and swift 3.1 is supported. 

See my note at then bottom of the Adobe ticket. And please vote. I would like to use Xcode 9 iOS 11 features.
https://tracker.adobe.com/#/view/AIR-4198407

The error you are getting:
You need to explicitly have the MinimumOSVersion set in your AIR app manifest like so. See the example project provided.
```
<array>
                <!-- iPhone and iPod touch devices -->
                <string>1</string>
                <!-- iPad devices -->
                <string>2</string>
            </array>
             <key>MinimumOSVersion</key>
            <string>9.0</string>
```

**Comment by tuarua** [comment]
P.S. If you really want to use Xcode 9 iOS 11 features then you can resign the compiled ipa before installing on device using
https://bitbucket.org/xgiovio/ios-ipa-resign/src

However, that would be a slow development process.
Am hoping Adobe can support iOS 11 signing ASAP

**Comment by urthling** [comment]
Voted - and understood - ty for explaining the issue and for the workaround.  Very much looking forward to using your project with iOS 11

**Comment by tuarua** [comment]
AIR 28 beta now supports Swift4 and Xcode 9.0
Project will be updated for that release in December

**Comment by tuarua** [comment]
iOS 11 and Xcode 9.1 supported with AIR 28
