### ISSUE TITLE
Error linking applications on Windows and Mac with older XCode (e.g. 10)

### ISSUE THREAD

**Issue by mrchnk** [tuarua/Swift-IOS-ANE#43]
You receive linking errors while packaging applications with provided swift stubs (text-based tbd-s). 

The reason is ld64 from AIR SDK does not support `tbd` version 4 (that format used currently in AIRSDK_Additions). It is possible to use another version of `tbd` format. I found that version 1 and 2 are supported. 

Also, some symbols are different on `iphoneos` and `iphonesimulator` platforms. Fortunately, you can list all that symbols in one file for different architectures.

Here are swift 5.0 stubs for iphoneos and iphonesumulator merged into v1 tbds:

[stub.zip](https://github.com/tuarua/Swift-IOS-ANE/files/6479121/stub.zip)

**Comment by tuarua** [comment]
Is there a scriptable way of generating these?

Anytime I update Xcode version I copy these out of Xcode. For example when Xcode 12 is released there will likely be new Apple packages for iOS15

The main reason the tbds are included in AIRSDK_Additions is to support Firebase-ANE as Firebase are static libraries.

It's not important to me to support old versions of Xcode.

**Comment by mrchnk** [comment]
I used [inoahdev/tbd](https://github.com/inoahdev/tbd) to generate tbd files of specific format from dylib, after that I used a hand-written script to merge different architectures. That could be scripted using that way, but it seems too complicated.

I'm not sure are you looking for Windows support as a build host or not, but it is impossible to package AIR applications with Firebase-ANE using provided AIRSDK_Additions on Windows (same as Mac without Xcode 12) with TBD v4.

**Comment by tuarua** [comment]
I don't officially support Windows for iOS ANEs. 
There are too many problems in general with AIR iOS and Windows in more recent years as the iOS platform has gotten significantly more complicated since AIR 3.0 (dynamic frameworks, assets.car, storyboards, swift, signing, etc etc).

The same goes for the possibility of supporting older Xcode. It all takes time. Unless someone is willing to pay/sponsor me to support their legacy setup then there is no incentive on my part to do so.

That being said if I was provided with a script to generate the tbds consistently I would consider adding that.
